// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHdxlF3T2oN-Bs-rjcnIIUFFo-eErcgRw',
    appId: '1:485444861937:web:5630bbe24e3de32eb5ce50',
    messagingSenderId: '485444861937',
    projectId: 'math-game-dev-2235d',
    authDomain: 'math-game-dev-2235d.firebaseapp.com',
    storageBucket: 'math-game-dev-2235d.appspot.com',
    measurementId: 'G-SN8BLD8LN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDntGLqePoAYvCo-2cWvIVDTFp18WSZbE0',
    appId: '1:485444861937:android:31754198af4d2a47b5ce50',
    messagingSenderId: '485444861937',
    projectId: 'math-game-dev-2235d',
    storageBucket: 'math-game-dev-2235d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBApIXI8pQ76J7h4MQZwEWJQa7nhGnETa0',
    appId: '1:485444861937:ios:57f6fb0ef3404a9cb5ce50',
    messagingSenderId: '485444861937',
    projectId: 'math-game-dev-2235d',
    storageBucket: 'math-game-dev-2235d.appspot.com',
    iosBundleId: 'com.example.basic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBApIXI8pQ76J7h4MQZwEWJQa7nhGnETa0',
    appId: '1:485444861937:ios:7525630dab51f73db5ce50',
    messagingSenderId: '485444861937',
    projectId: 'math-game-dev-2235d',
    storageBucket: 'math-game-dev-2235d.appspot.com',
    iosBundleId: 'com.example.basic.RunnerTests',
  );
}
